# Default values for crud-app in the prod environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1  # Typically lower for development environments

image:
  repository: amits64/crud-app
  pullPolicy: IfNotPresent
  tag: "prod-${BUILD_NUMBER}"  # Use a specific tag for prod

imagePullSecrets:
  - name: my-registry-secret  # Optional, if you use private registry

nameOverride: "crud-app-prod"
fullnameOverride: "crud-app-prod"

serviceAccount:
  create: true
  annotations: {}
  name: "crud-app-prod-sa"  # Specific service account for prod

podAnnotations:
  kubernetes.io/cluster-service: "true"

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false  # Ingress typically not used in prod
  className: ""
  annotations: {}
  hosts:
    - host: prod.chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false  # Autoscaling usually disabled in prod
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

nodeSelector:
  environment: prod

tolerations:
  - key: "environment"
    operator: "Equal"
    value: "prod"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "kubernetes.io/role"
              operator: "In"
              values:
                - "prod"
