apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
      - name: node-crud-container
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "10.102.255.53"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "Kubernetes@1993"
